# Generated by Django 2.2.1 on 2021-03-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_container_protocol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='Text id')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Text content')),
            ],
        ),
    ]
