# Generated by Django 2.2.1 on 2021-04-08 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='computing',
            name='access_method',
            field=models.CharField(default='NA', max_length=255, verbose_name='Computing Access method'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='computingsysconf',
            name='computing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_sys_conf', to='core_app.Computing'),
        ),
        migrations.AlterField(
            model_name='computinguserconf',
            name='computing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_user_conf', to='core_app.Computing'),
        ),
    ]
