# Generated by Django 2.2.1 on 2021-10-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_auto_20210408_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container',
            old_name='supports_pass_auth',
            new_name='supports_password_auth',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='tid',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='computing',
            name='access_method',
        ),
        migrations.RemoveField(
            model_name='computing',
            name='supports_docker',
        ),
        migrations.RemoveField(
            model_name='computing',
            name='supports_singularity',
        ),
        migrations.RemoveField(
            model_name='container',
            name='ports',
        ),
        migrations.RemoveField(
            model_name='container',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='container',
            name='supports_user_auth',
        ),
        migrations.RemoveField(
            model_name='container',
            name='type',
        ),
        migrations.RemoveField(
            model_name='task',
            name='access_method',
        ),
        migrations.RemoveField(
            model_name='task',
            name='auth_pass',
        ),
        migrations.RemoveField(
            model_name='task',
            name='auth_user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='task',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='task',
            name='port',
        ),
        migrations.AddField(
            model_name='computing',
            name='access_mode',
            field=models.CharField(default='ssh+cli', max_length=36, verbose_name='Computing resource access (control) mode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computing',
            name='auth_mode',
            field=models.CharField(default='user_keys', max_length=36, verbose_name='Computing resource authentication mode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computing',
            name='container_runtimes',
            field=models.CharField(default='singularity', max_length=256, verbose_name='Computing resource container runtimes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computing',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Container description'),
        ),
        migrations.AddField(
            model_name='computing',
            name='wms',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Computing resource WMS'),
        ),
        migrations.AddField(
            model_name='container',
            name='arch',
            field=models.CharField(default='x86_64', max_length=36, verbose_name='Container architecture'),
        ),
        migrations.AddField(
            model_name='container',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Container description'),
        ),
        migrations.AddField(
            model_name='container',
            name='interface_port',
            field=models.IntegerField(blank=True, null=True, verbose_name='Container interface default port'),
        ),
        migrations.AddField(
            model_name='container',
            name='interface_protocol',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Container interface protocol'),
        ),
        migrations.AddField(
            model_name='container',
            name='interface_transport',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Container interface protocol'),
        ),
        migrations.AddField(
            model_name='container',
            name='os',
            field=models.CharField(default='linux', max_length=36, verbose_name='Container operating system'),
        ),
        migrations.AddField(
            model_name='container',
            name='tag',
            field=models.CharField(default='latest', max_length=255, verbose_name='Container image'),
        ),
        migrations.AddField(
            model_name='task',
            name='interface_ip',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Task interface ip address'),
        ),
        migrations.AddField(
            model_name='task',
            name='interface_port',
            field=models.IntegerField(blank=True, null=True, verbose_name='Task interface port'),
        ),
        migrations.AddField(
            model_name='task',
            name='proxy_token',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Token for proxy auth if any'),
        ),
        migrations.AddField(
            model_name='task',
            name='requires_proxy',
            field=models.BooleanField(default=True, verbose_name='Does the task require a proxy?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='requires_tunnel',
            field=models.BooleanField(default=True, verbose_name='Does the task require a tunnel to be opened?'),
            preserve_default=False,
        ),
    ]
