# Generated by Django 2.2.1 on 2021-11-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_auto_20211030_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container',
            old_name='supports_password_auth',
            new_name='supports_interface_auth',
        ),
        migrations.RenameField(
            model_name='container',
            old_name='supports_dynamic_ports',
            new_name='supports_setting_interface_port',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='tunnel_port',
            new_name='tcp_tunnel_port',
        ),
        migrations.RemoveField(
            model_name='task',
            name='proxy_token',
        ),
        migrations.RemoveField(
            model_name='task',
            name='requires_tunnel',
        ),
        migrations.AddField(
            model_name='task',
            name='auth_token',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='A one-time token for proxy or task interface auth if any'),
        ),
        migrations.AddField(
            model_name='task',
            name='requires_proxy_auth',
            field=models.BooleanField(default=False, verbose_name='Does the task require interface authentication to be enforced at proxy-level?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='requires_tcp_tunnel',
            field=models.BooleanField(default=True, verbose_name='Does the task require a tunnel to be opened for accessing its interface?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='requires_proxy',
            field=models.BooleanField(verbose_name='Does the task require a proxy for accessing its interface?'),
        ),
    ]
