# Generated by Django 2.2.1 on 2021-11-03 12:28

from django.conf import settings
from django.db import migrations, models

# Load database-dependent JSON field
if 'sqlite' in settings.DATABASES['default']['ENGINE']:
    from rosetta.core_app.fields import JSONField
else:
    from django.contrib.postgres.fields import JSONField

class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_auto_20211102_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='interface_port',
            field=models.IntegerField(blank=True, null=True, verbose_name='Container interface port'),
        ),
        migrations.AlterField(
            model_name='container',
            name='supports_interface_auth',
            field=models.BooleanField(default=False, verbose_name='Does the container interface support authentication?'),
        ),
        migrations.AlterField(
            model_name='container',
            name='supports_setting_interface_port',
            field=models.BooleanField(default=False, verbose_name='Does the container support setting a custom interface port?'),
        ),
        migrations.AlterField(
            model_name='task',
            name='auth_token',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='A one-time token for proxy or interface authentication'),
        ),
        migrations.AlterField(
            model_name='task',
            name='computing_options',
            field=JSONField(blank=True, null=True, verbose_name='Task computing options'),
        ),
        migrations.AlterField(
            model_name='task',
            name='extra_binds',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='Task container extra binds'),
        ),
    ]
