# Generated by Django 2.2.1 on 2021-11-03 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_auto_20211103_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container',
            old_name='supports_setting_interface_port',
            new_name='supports_custom_interface_port',
        ),
    ]
