# Generated by Django 2.2.1 on 2021-11-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0009_auto_20211103_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_power_user',
            field=models.BooleanField(default=False, verbose_name='Power user status'),
        ),
    ]
