# Generated by Django 2.2.1 on 2021-11-08 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0011_storage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='extra_binds',
        ),
    ]
