# Generated by Django 2.2.1 on 2021-11-08 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0013_auto_20211108_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keypair',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
