# Generated by Django 2.2.1 on 2021-11-08 17:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0015_auto_20211108_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='extra_conf',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
