# Generated by Django 2.2.1 on 2021-11-08 17:53

from django.conf import settings
from django.db import migrations

# Load database-dependent JSON field
if 'sqlite' in settings.DATABASES['default']['ENGINE']:
    from rosetta.core_app.fields import JSONField
else:
    from django.contrib.postgres.fields import JSONField

class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0015_auto_20211108_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='extra_conf',
            field=JSONField(blank=True, null=True),
        ),
    ]
