# Generated by Django 2.2.1 on 2021-11-08 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0016_profile_extra_conf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='extra_conf',
            new_name='extra_confs',
        ),
    ]
