# Generated by Django 2.2.1 on 2021-11-08 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0017_auto_20211108_1759'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComputingUserConf',
        ),
    ]
