# Generated by Django 2.2.1 on 2021-11-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0018_delete_computinguserconf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='Page id')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Page content')),
            ],
        ),
        migrations.DeleteModel(
            name='Text',
        ),
    ]
