# Generated by Django 2.2.1 on 2021-11-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0019_auto_20211115_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auth',
            field=models.CharField(default='oidc', max_length=36, verbose_name='User auth mode'),
            preserve_default=False,
        ),
    ]
