# Generated by Django 2.2.1 on 2021-11-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0020_profile_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='interface_auth_user',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Interface auth fixed user if any'),
        ),
    ]
