# Generated by Django 2.2.1 on 2021-11-21 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0021_container_interface_auth_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computing',
            old_name='container_runtimes',
            new_name='container_runtime',
        ),
    ]
