# Generated by Django 2.2.1 on 2021-11-21 13:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0022_auto_20211121_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computing',
            name='container_runtime',
        ),
        migrations.AddField(
            model_name='computing',
            name='container_runtimes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=['docker'], verbose_name='Container runtimes'),
            preserve_default=False,
        ),
    ]
