# Generated by Django 2.2.1 on 2021-11-21 13:42

from django.conf import settings
from django.db import migrations

# Load database-dependent JSON field
if 'sqlite' in settings.DATABASES['default']['ENGINE']:
    from rosetta.core_app.fields import JSONField
else:
    from django.contrib.postgres.fields import JSONField

class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0022_auto_20211121_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computing',
            name='container_runtime',
        ),
        migrations.AddField(
            model_name='computing',
            name='container_runtimes',
            field=JSONField(default=['docker'], verbose_name='Container runtimes'),
            preserve_default=False,
        ),
    ]
