# Generated by Django 2.2.1 on 2021-11-21 13:42

from django.conf import settings
from django.db import migrations

# Load database-dependent JSON field
if 'sqlite' in settings.DATABASES['default']['ENGINE']:
    from rosetta.core_app.fields import JSONField
else:
    from django.contrib.postgres.fields import JSONField

class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0023_auto_20211121_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='computing',
            name='emulated_archs',
            field=JSONField(blank=True, null=True, verbose_name='Emulated architectures'),
        ),
    ]
