# Generated by Django 2.2.1 on 2021-11-21 13:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0023_auto_20211121_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='computing',
            name='emulated_archs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Emulated architectures'),
        ),
    ]
