# Generated by Django 2.2.1 on 2021-11-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0024_computing_emulated_archs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container',
            old_name='arch',
            new_name='image_arch',
        ),
        migrations.RenameField(
            model_name='container',
            old_name='image',
            new_name='image_name',
        ),
        migrations.RenameField(
            model_name='container',
            old_name='os',
            new_name='image_os',
        ),
        migrations.RenameField(
            model_name='container',
            old_name='tag',
            new_name='image_tag',
        ),
        migrations.AddField(
            model_name='container',
            name='image_digest',
            field=models.CharField(blank=True, max_length=96, null=True, verbose_name='SHA 256 digest'),
        ),
    ]
