# Generated by Django 2.2.1 on 2021-11-23 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0025_auto_20211122_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='image_arch',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Architecture'),
        ),
        migrations.AlterField(
            model_name='container',
            name='image_os',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Operating system'),
        ),
    ]
