# Generated by Django 2.2.1 on 2021-11-24 00:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0026_auto_20211123_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='computing',
            name='supported_archs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Supported architectures'),
        ),
    ]
