# Generated by Django 2.2.1 on 2021-11-24 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0027_computing_supported_archs'),
    ]

    operations = [
        migrations.AddField(
            model_name='computing',
            name='arch',
            field=models.CharField(default='amd64', max_length=255, verbose_name='Architecture'),
            preserve_default=False,
        ),
    ]
