# Generated by Django 2.2.1 on 2021-12-18 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0028_computing_arch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computing',
            old_name='container_runtimes',
            new_name='container_engines',
        ),
    ]
