# Generated by Django 2.2.1 on 2021-12-18 23:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0029_auto_20211218_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computing',
            name='container_engines',
            field=django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Container engines/runtimes'),
        ),
    ]
