# Generated by Django 2.2.1 on 2021-12-18 23:55

from django.conf import settings
from django.db import migrations

# Load database-dependent JSON field
if 'sqlite' in settings.DATABASES['default']['ENGINE']:
    from rosetta.core_app.fields import JSONField
else:
    from django.contrib.postgres.fields import JSONField

class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0029_auto_20211218_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computing',
            name='container_engines',
            field=JSONField(verbose_name='Container engines/runtimes'),
        ),
    ]
