# Generated by Django 2.2.1 on 2022-01-16 18:40

from django.conf import settings
from django.db import migrations

# Load database-dependent JSON field
if 'sqlite' in settings.DATABASES['default']['ENGINE']:
    from rosetta.core_app.fields import JSONField
else:
    from django.contrib.postgres.fields import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0030_auto_20211218_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='env_vars',
            field=JSONField(blank=True, null=True, verbose_name='Container env vars'),
        ),
    ]
