# Generated by Django 2.2.1 on 2022-04-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0031_container_env_vars'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='browsable',
            field=models.BooleanField(default=False, verbose_name='Browsable in the file manager?'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='bind_path',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='Bind path'),
        ),
    ]
