# Generated by Django 2.2.1 on 2022-04-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0032_auto_20220409_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='browsable',
            field=models.BooleanField(default=True, verbose_name='Browsable in the file manager?'),
        ),
    ]
