# Generated by Django 2.2.1 on 2023-10-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0033_auto_20220410_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='requires_tcp_tunnel',
            field=models.BooleanField(verbose_name='Requires TCP tunnel'),
        ),
    ]
