# Generated by Django 2.2.1 on 2023-10-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0034_auto_20231007_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.AddField(
            model_name='task',
            name='job_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Job ID'),
        ),
        migrations.AddField(
            model_name='task',
            name='process_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Process ID'),
        ),
    ]
