# Generated by Django 2.2.1 on 2023-10-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0035_auto_20231007_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='disable_http_basicauth_embedding',
            field=models.BooleanField(default=False, verbose_name='Disable HTTP basicauth credentials embedding'),
        ),
    ]
