# Generated by Django 2.2.1 on 2025-03-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0036_container_disable_http_basicauth_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='read_only',
            field=models.BooleanField(default=False, verbose_name='Read only? (if supported)'),
        ),
    ]
